### ISSUE TITLE
[Tracker] feathericons.com 2.0 progress

### ISSUE THREAD

**Issue by zaydek** [feathericons/feathericons.com#623]
This issue is dedicated to documenting the progress of the 2.0 feathericons.com client:

- [x] **Color theming:**
  - [x] From looking at https://primer.style/css/utilities/colors it looks like there’s a pretty limited suite of colors to choose from. Instead, I’ll probably opt for the [Tailwind UI color palette](https://tailwindui.com/documentation#how-tailwindcss-ui-extends-tailwind) or the experimental [Tailwind 2.0 color palette](https://github.com/tailwindlabs/tailwindcss/releases#new-color-palette) which has better support for balancing color brightness between different colors.
- [ ] **Core features:**
    - [ ] Download SVG (legacy user expectation)
    - [x] Download all SVGs (legacy user expectation)
    - [ ] Copy SVG (more current user expectation)
    - [ ] Open SVG in a new page? (better for bookmarking, sharing, and possibly SEO)
    - [ ] Copy JSX (for React apps)
    - [ ] Copy icon name, e.g. `alert-triangle`, `AlertTriangle`
- [ ] **Light mode, dark mode:**
    - [ ] The difference here versus the current client would be adding support for a transition and _possibly_ persisting dark mode to localStorage
- [x] **Add buttons to share Feathericons on Twitter, possibly Facebook**
  - [x] This basically means embedding a link that links out to a URL like:
    - [x] E.g. [Say thank you on Twitter!](https://twitter.com/intent/tweet?text=Thanks%20@colebemis%20for%20Feathericons%20and%20@username_ZAYDEK%20for%20feathericons.com%202.0!&url=https://feathericons.com)
- [ ] **Improved search UI**
  - [ ] We can custom render a search highlight based on the search query. This does not come with an obvious performance hit and makes for a more streamlined, focused UI. [See this tweet for reference.](https://twitter.com/username_ZAYDEK/status/1294961380345470976?s=20)
    - [ ] Note that searching against tags complicates this. I’m not sure how to handle this common edge-case.
- [ ] ~~**The sticky search bar should _probably_ be disabled on mobile devices to CPU-throttling**~~
- [ ] **Input controls:**
  - [ ] Make sure input controls feel responsive
  - [ ] Make sure input (and possibly dark mode) persist to localStorage, and the reset button or equivalent purges the cache
- [ ] **SEO:**
  - [x] Given the existing user base, we would be unwise to roll `create-react-app`. Gatsby is confusing to me, so I’m going to experiment with NextJS’s modern features to build feathericons.com as a server-side generated (SSG) app that we can easily auto-deploy to Netlify or drag-and-drop if needed (no server needed).
  - [x] _It would be really cool_ if icons can be viewed independently for sharing purposes, which also potentially boosts SEO.
  - [ ] Alternatively, we may want to implement a bookmarking feature to aggregate icons in one place to download or copy as SVG in one place. @fayazara inspired this feature with his bookmarking feature on https://appydev.co.
    - [ ] @marcmll has request a very similar feature; bulk download / copy
- [x] **Improve readme for prospective contributors**
	- [x] Contributing should welcomed and appreciated
- [ ] **Code-generation:**
  - [ ] _It would  be really cool_ if we can render syntax highlighted code for an icon on click to help communicate to users Feathericons _is just code_. We should also provide a tooltip explaining that **SVG icons copied from Feathericons can be directly copied to Figma**, therefore encouraging use of https://feathericons.com.
    - [ ] @dimitrisraptis96 inspired this concept
